#pragma once

#include <absl/log/check.h>

#define S2GEOGRAPHY_DCHECK DCHECK
#define S2GEOGRAPHY_DCHECK_LE DCHECK_LE
#define S2GEOGRAPHY_DCHECK_LT DCHECK_LT
#define S2GEOGRAPHY_DCHECK_GE DCHECK_GE
#define S2GEOGRAPHY_DCHECK_GT DCHECK_GT

#define S2GEOGRAPHY_UNUSED(x) (void)(x)
